Region: us-west-2
CustomS3Bucket: dev-nlcd-parallelcluster-testbucket
Image:
  Os: alinux2
  CustomAmi: ami-0872138b35b419480
HeadNode:
  InstanceType: t3.large
  Networking:
    SubnetId: subnet-06cf6942c47c4958d
    SecurityGroups:
      - sg-002f447f31043cbed
  Ssh:
    KeyName: butzer@IGSKMNCNLT01529
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::081515586180:policy/developer-policy
      - Policy: arn:aws:iam::081515586180:policy/nlcd-developer-s3-access-policy
    S3Access:
      - BucketName: dev-nlcd-developer
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    Dns:
      DisableManagedDns: true
      UseEc2Hostnames: true
  SlurmQueues:
  - Name: eco
    ComputeResources:
    - Name: nodes 
      Instances:
      - InstanceType: m6i.4xlarge
      MinCount: 0
      MaxCount: 16
    Networking:
      SubnetIds:
      - subnet-06cf6942c47c4958d
      SecurityGroups:
        - sg-002f447f31043cbed
    Image:
      CustomAmi: ami-0872138b35b419480
    Iam:
      AdditionalIamPolicies:
        - Policy: arn:aws:iam::081515586180:policy/developer-policy
        - Policy: arn:aws:iam::081515586180:policy/nlcd-developer-s3-access-policy
      S3Access:
        - BucketName: dev-nlcd-developer
  - Name: big
    ComputeResources:
    - Name: big 
      Instances:
      - InstanceType: m6i.8xlarge
      MinCount: 0
      MaxCount: 8
    Networking:
      SubnetIds:
      - subnet-06cf6942c47c4958d
      SecurityGroups:
        - sg-002f447f31043cbed
    Image:
      CustomAmi: ami-0872138b35b419480
    Iam:
      AdditionalIamPolicies:
        - Policy: arn:aws:iam::081515586180:policy/developer-policy
        - Policy: arn:aws:iam::081515586180:policy/nlcd-developer-s3-access-policy
      S3Access:
        - BucketName: dev-nlcd-developer
Iam:
  PermissionsBoundary: arn:aws:iam::081515586180:policy/csr-Developer-Permissions-Boundary
SharedStorage:
  - MountDir: /efs
    Name: pcluster-efs
    StorageType: Efs
    EfsSettings:
      FileSystemId: fs-08948e44ec4986095
